platform: x64

os: Visual Studio 2015

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - mkdir build
  - cd build
  - cmake ../ -G "NMake Makefiles"
  - nmake
  - nmake install


